---
- name: Configure Windows EC2 Instances in Elastic Beanstalk
  hosts: windows
  tasks:
    - name: Ensure C:\temp directory exists
      win_file:
        path: 'C:\temp'
        state: directory

    - name: Download WebDeploy Installer
      win_get_url:
        url: "https://my-s3-bucket-for-jenkins-pipeline-setup.s3.amazonaws.com/webdeploy_amd64_en-US.msi"
        dest: "C:\\temp\\WebDeploy_x64.msi"

    - name: Install WebDeploy
      win_package:
        path: 'C:\\temp\\WebDeploy_x64.msi'
        state: present
        arguments: '/quiet'

    - name: Create WebDeploy Admin User
      win_user:
        name: "webdeployadmin"
        password: "{{ lookup('env', 'WEBDEPLOYADMIN_PASSWORD') }}"
        state: present

    - name: Add WebDeploy Admin to Administrators Group
      win_group_membership:
        name: Administrators
        members: webdeployadmin
        state: present

    # Ensure login.aspx is added to Default Documents
    - name: Ensure login.aspx is added to Default Documents
      win_shell: |
        Import-Module WebAdministration
        $site = Get-Website -Name 'Default Web Site'
        if ($site) {
          $defaultDocs = Get-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.webServer/defaultDocument/files" -name "value" -location 'Default Web Site'
          if ($defaultDocs -notcontains 'login.aspx') {
            Add-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.webServer/defaultDocument/files" -name "." -value @{value='login.aspx'} -location 'Default Web Site'
            Write-Host "Added login.aspx to default documents."
          } else {
            Write-Host "login.aspx already exists in the default documents."
          }
        }

    # Check if HTTP binding exists, if not, add it
    - name: Check if HTTP binding exists on port 80
      win_shell: |
        Import-Module WebAdministration
        $bindings = Get-WebBinding -Name 'Default Web Site' | Where-Object { $_.bindingInformation -like '*:80:' }
        if ($bindings -eq $null) {
          Write-Host "No HTTP binding on port 80 exists. Adding..."
          New-WebBinding -Name 'Default Web Site' -Protocol http -Port 80
        } else {
          Write-Host "HTTP binding on port 80 already exists."
        }

    - name: Ensure IIS AppPool 'DefaultAppPool' is started
      win_shell: |
        Import-Module WebAdministration
        $appPoolState = Get-WebAppPoolState -Name 'DefaultAppPool'
        if ($appPoolState -eq 'Stopped') {
          Start-WebAppPool -Name 'DefaultAppPool'
          Write-Host "App Pool started."
        } else {
          Write-Host "App Pool is already running."
        }

    - name: Stop IIS Management Service before identity change
      win_service:
        name: WMSVC
        state: stopped

    - name: Change IIS Management Service identity to Windows/IIS Management credentials
      win_shell: |
        Import-Module WebAdministration
        Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/anonymousAuthentication" -name "identity" -value "IIS_IUSRS"

    - name: Start IIS Management Service after identity change
      win_service:
        name: WMSVC
        state: started

    - name: Restart IIS to ensure all services are running
      win_service:
        name: W3SVC
        state: restarted
