---
- name: Configure Windows EC2 Instances in Elastic Beanstalk
  hosts: windows
  tasks:
    - name: Ensure C:\temp directory exists
      win_file:
        path: 'C:\temp'
        state: directory

    - name: Download WebDeploy Installer
      win_get_url:
        url: "https://my-s3-bucket-for-jenkins-pipeline-setup.s3.amazonaws.com/webdeploy_amd64_en-US.msi"
        dest: "C:\\temp\\WebDeploy_x64.msi"

    - name: Install WebDeploy
      win_package:
        path: 'C:\\temp\\WebDeploy_x64.msi'
        state: present
        arguments: '/quiet'

    - name: Create WebDeploy Admin User with password never expiring
      win_user:
        name: "WDeployAdmin"
        password: "{{ lookup('env', 'WEBDEPLOYADMIN_PASSWORD') }}"
        state: present
        password_never_expires: yes

    - name: Add WebDeploy Admin to Administrators Group
      win_group_membership:
        name: Administrators
        members: WDeployAdmin
        state: present

    - name: Add WebDeployConfigWriter User with password never expiring
      win_user:
        name: "WDeployConfigWriter"
        password: "{{ lookup('env', 'WEBDEPLOYADMIN_PASSWORD') }}"
        state: present
        password_never_expires: yes

    - name: Add WebDeployConfigWriter to Administrators Group
      win_group_membership:
        name: Administrators
        members: WDeployConfigWriter
        state: present

    - name: Add login.aspx to Default Documents at Default Web Site level
      win_shell: |
        Import-Module WebAdministration
        $defaultDocsPath = "MACHINE/WEBROOT/APPHOST/Default Web Site"
        $defaultDocs = Get-WebConfigurationProperty -pspath $defaultDocsPath -filter "system.webServer/defaultDocument/files" -name "."
    
        # Check if 'login.aspx' already exists
        if ($defaultDocs.collection.value -notcontains 'login.aspx') {
            Add-WebConfigurationProperty -pspath $defaultDocsPath -filter "system.webServer/defaultDocument/files" -name "." -value @{value='login.aspx'}
            Write-Host "'login.aspx' added to Default Documents for Default Web Site"
        } else {
            Write-Host "'login.aspx' already exists in Default Documents for Default Web Site"
        }
      args:
        executable: "powershell"

    - name: Start DefaultAppPool if not running
      win_shell: |
        Import-Module WebAdministration
        $appPool = Get-WebAppPoolState -Name 'DefaultAppPool'
        if ($appPool -ne 'Started') {
          Start-WebAppPool -Name 'DefaultAppPool'
          Write-Host "DefaultAppPool started."
        } else {
          Write-Host "DefaultAppPool is already running."
        }

    - name: Ensure Default Web Site is running
      win_shell: |
        Import-Module WebAdministration
        $site = Get-Website -Name 'Default Web Site'
        if ($site.state -ne 'Started') {
          Start-Website -Name 'Default Web Site'
          Write-Host "Default Web Site started."
        } else {
          Write-Host "Default Web Site is already running."
        }

    - name: Stop IIS Management Service before identity change
      win_service:
        name: WMSVC
        state: stopped

    - name: Check if SSL certificate exists
      win_shell: |
        $cert = Get-ChildItem Cert:\\LocalMachine\\My | Where-Object { $_.DnsName -eq 'office-deployment' }
        if ($cert) {
          Write-Host "Certificate already exists: $($cert.Thumbprint)"
        } else {
          Write-Host "Certificate not found. A new one will be created."
        }
      register: cert_check
      failed_when: cert_check.rc != 0 and cert_check.stdout | search('Certificate not found') == false

    - name: Create a self-signed SSL certificate only if not already present
      win_shell: |
        Import-Module WebAdministration
        $cert = New-SelfSignedCertificate -DnsName "office-deployment" -CertStoreLocation "cert:\\LocalMachine\\My" -FriendlyName "OfficeDeploymentCertificate"
        Write-Host "Self-signed certificate 'OfficeDeploymentCertificate' created."
      when: cert_check.stdout | search('Certificate not found')

    - name: Assign the SSL certificate and enable remote connections with identity change
      win_shell: |
        $cert = Get-ChildItem Cert:\\LocalMachine\\My | Where-Object { $_.FriendlyName -eq 'OfficeDeploymentCertificate' }
        if ($cert) {
          Write-Host "Assigning SSL certificate $($cert.Thumbprint) to IIS Management and applying identity change."
          
          # Change Identity settings (e.g., set a specific identity if required)
          Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/siteDefaults/applicationPool" -name "processModel.identityType" -value "SpecificUser"
          Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/siteDefaults/applicationPool" -name "processModel.userName" -value "WDeployAdmin"
          Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/sites/siteDefaults/applicationPool" -name "processModel.password" -value "{{ lookup('env', 'WEBDEPLOYADMIN_PASSWORD') }}"

          # Enable remote management with SSL
          Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/management" -name "enableRemoteManagement" -value $true
          Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/management" -name "SslCertificateHash" -value $cert.Thumbprint
          
          Write-Host "SSL certificate and remote connection applied successfully."
        } else {
          Write-Host "Certificate not found. Exiting."
          exit 1
        }

    - name: Start IIS Management Service after applying all configurations
      win_service:
        name: WMSVC
        state: started
      ignore_errors: no
