---
- name: Configure Windows EC2 Instances in Elastic Beanstalk
  hosts: windows
  tasks:
    - name: Ensure C:\temp directory exists
      win_file:
        path: 'C:\temp'
        state: directory

    - name: Download WebDeploy Installer
      win_get_url:
        url: "https://my-s3-bucket-for-jenkins-pipeline-setup.s3.amazonaws.com/webdeploy_amd64_en-US.msi"
        dest: "C:\\temp\\WebDeploy_x64.msi"

    - name: Install WebDeploy
      win_package:
        path: 'C:\\temp\\WebDeploy_x64.msi'
        state: present
        arguments: '/quiet'

    - name: Create WebDeploy Admin User
      win_user:
        name: "webdeployadmin"
        password: "{{ lookup('env', 'WEBDEPLOYADMIN_PASSWORD') }}"
        state: present

    - name: Add WebDeploy Admin to Administrators Group
      win_group_membership:
        name: Administrators
        members: webdeployadmin
        state: present

    - name: Add WebDeployConfigWriter to Group
      win_user:
        name: "WDeployConfigWriter"
        password: "{{ lookup('env', 'WEBDEPLOYADMIN_PASSWORD') }}"
        state: present

    - name: Add WebDeployConfigWriter to Administrators Group
      win_group_membership:
        name: Administrators
        members: WDeployConfigWriter
        state: present

    - name: Ensure login.aspx is added to Default Documents (with debug logging)
      win_shell: |
        Import-Module WebAdministration
        $site = Get-Website -Name 'Default Web Site'
        if ($site) {
          Write-Host "Default Web Site exists."
          $defaultDocs = Get-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.webServer/defaultDocument/files" -name "value" -location 'Default Web Site'
          if ($defaultDocs -notcontains 'login.aspx') {
            Add-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.webServer/defaultDocument/files" -name "." -value @{value='login.aspx'} -location 'Default Web Site'
            Write-Host "Added login.aspx to default documents."
          } else {
            Write-Host "login.aspx already exists in the default documents."
          }
        } else {
          Write-Host "Default Web Site does not exist!"
        }
      register: login_aspx_result
      retries: 3
      delay: 5
      until: login_aspx_result.rc == 0

    - name: Start Default Web Site if stopped (enforce start with detailed logging)
      win_shell: |
        Import-Module WebAdministration
        $site = Get-Website -Name 'Default Web Site'
        if ($site.state -ne 'Started') {
          Write-Host "Starting Default Web Site..."
          Start-Website -Name 'Default Web Site'
        }
        $siteUpdated = Get-Website -Name 'Default Web Site'
        if ($siteUpdated.state -eq 'Started') {
          Write-Host "Default Web Site started successfully."
        } else {
          Write-Host "Failed to start Default Web Site!"
        }
      register: website_start_result
      retries: 3
      delay: 5
      until: website_start_result.rc == 0

    - name: Ensure DefaultAppPool is running and restart if necessary
      win_shell: |
        Import-Module WebAdministration
        $appPool = Get-WebAppPoolState -Name 'DefaultAppPool'
        if ($appPool -ne 'Started') {
          Write-Host "Starting DefaultAppPool..."
          Start-WebAppPool -Name 'DefaultAppPool'
          Write-Host "DefaultAppPool started."
        } else {
          Write-Host "DefaultAppPool is already running."
        }

    - name: Stop IIS Management Service before identity change
      win_service:
        name: WMSVC
        state: stopped

    - name: Create a self-signed SSL certificate (with detailed logging)
      win_shell: |
        Import-Module WebAdministration
        Write-Host "Creating self-signed certificate..."
        $cert = New-SelfSignedCertificate -DnsName "office-deployment" -CertStoreLocation "cert:\LocalMachine\My"
        if ($cert) {
          Write-Host "Self-signed certificate 'office-deployment' created successfully."
        } else {
          Write-Host "Failed to create SSL certificate."
        }

    - name: Enable Remote Connections and set SSL certificate in IIS Management Service (detailed logging)
      win_shell: |
        Import-Module WebAdministration
        $cert = Get-ChildItem Cert:\LocalMachine\My | Where-Object { $_.FriendlyName -eq 'office-deployment' }
        if ($cert) {
          Write-Host "Binding SSL certificate to IIS Management Service..."
          Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/management" -name "enableRemoteManagement" -value $true
          Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -filter "system.applicationHost/management" -name "SslCertificateHash" -value $cert.Thumbprint
          Write-Host "Remote connections enabled and SSL certificate bound to IIS Management Service."
        } else {
          Write-Host "SSL certificate not found! Failed to bind certificate."
        }
      register: remote_enable_result
      retries: 3
      delay: 5
      until: remote_enable_result.rc == 0

    - name: Start IIS Management Service after changes
      win_service:
        name: WMSVC
        state: started

    - name: Ensure DefaultAppPool is still running after all changes
      win_shell: |
        Import-Module WebAdministration
        $appPool = Get-WebAppPoolState -Name 'DefaultAppPool'
        if ($appPool -ne 'Started') {
          Start-WebAppPool -Name 'DefaultAppPool'
          Write-Host "DefaultAppPool started after all changes."
        } else {
          Write-Host "DefaultAppPool is still running."
        }

    - name: Ensure Default Web Site is still running after all changes
      win_shell: |
        Import-Module WebAdministration
        $site = Get-Website -Name 'Default Web Site'
        if ($site.state -ne 'Started') {
          Start-Website -Name 'Default Web Site'
          Write-Host "Default Web Site started after all changes."
        } else {
          Write-Host "Default Web Site is still running."
        }
