---
- name: Configure Windows EC2 Instances in Elastic Beanstalk
  hosts: windows
  tasks:
    - name: Ensure C:\temp directory exists
      win_file:
        path: 'C:\temp'
        state: directory

    - name: Download WebDeploy Installer
      win_get_url:
        url: "https://my-s3-bucket-for-jenkins-pipeline-setup.s3.amazonaws.com/webdeploy_amd64_en-US.msi"
        dest: "C:\\temp\\WebDeploy_x64.msi"

    - name: Install WebDeploy
      win_package:
        path: 'C:\\temp\\WebDeploy_x64.msi'
        state: present
        arguments: '/quiet'

    - name: Restart Web Management Service (WMSVC)
      win_service:
        name: WMSVC
        state: restarted

    - name: Add login.aspx to Default Documents for Default Web Site
      win_iis_website:
        name: Default Web Site
        state: started
        default_documents:
          - login.aspx

    - name: Ensure Default Web Site is running
      win_iis_website:
        name: Default Web Site
        state: started

    - name: Restart IIS to apply changes
      win_service:
        name: W3SVC
        state: restarted
